### ISSUE TITLE
400 Bad Request

### ISSUE THREAD

**Issue by Naeem775** [tsirysndr/mvola-node#3]
I copy pasted your example, and run it with a node js server but it's giving me 400 bad request error

**Comment by gaetan1903** [comment]
are you sure you fill your key in the env and name the env varriable correctly ?

**Comment by Naeem775** [comment]
yes, sorry for bothering you, i contacted the dev team and they told me it was a problem with sandbox.

**Comment by Naeem775** [comment]
yes, sorry for bothering you, i contacted the dev team and they told me it was a problem with sandbox,

**Comment by Naeem775** [comment]
sorry for bothering you, i contacted the dev team and they told me it was a problem with sandbox
